package com.payverse.walletservice.dto;

import jakarta.validation.constraints.NotNull;

public class CreateWalletRequest {

    @NotNull(message = "User ID is required")
    private Long userId;

    public CreateWalletRequest() {
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
}

//We need DTO because we do not ask for the wallet ID in the request, as it will be generated by the system. The DTO allows us to encapsulate the data we need for creating a wallet without exposing unnecessary details.
//DTO provides abstraction. It decouples the API contract from the database schema, allowing backend developers to change database design without breaking clients.