CREATE TABLE users (

    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    email VARCHAR(100) NOT NULL UNIQUE,

    phone VARCHAR(15) NOT NULL UNIQUE,

    password VARCHAR(255) NOT NULL,

    role ENUM('ADMIN','CUSTOMER','MERCHANT') NOT NULL,

    created_at DATETIME(6) NOT NULL

);